import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ProfileComponent from "@/components/ProfileComponent";
import Navigation from "@/components/Navigation";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900", "500"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="grid sm:grid-cols-[1.5fr_3fr_1fr] justify-center gap-3 items-center h-screen bg-custom-image">
          <div className="flex justify-center items-center">
            <ProfileComponent />
          </div>

          {/* Children inside 3fr width */}
          <div className="h-[95vh] overflow-y-scroll hide-scrollbar bg-[#ffffff] rounded-lg">
            {children}
          </div>

          {/* Navigation inside 1fr width and centered */}
          <div className="flex justify-center items-center">
            <Navigation />
          </div>
        </div>
      </body>
    </html>
  );
}
